name: Market Analysis Engine

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:      # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    environment: .env
    permissions:
      contents: write  # Need write permission to commit report

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Quant Engine
      env:
        CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      run: python quant_engine.py

    - name: Commit and Push Report
      run: |
        git config --global user.name 'QuantBot'
        git config --global user.email 'bot@noreply.github.com'
        git add MARKET_REPORT.md *.png
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generated Market Report [skip ci]"; git push)
